# Generated by Django 5.0.4 on 2026-06-13 07:20

import django.db.models.deletion
import django.utils.timezone
import email_reports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('microsoft365', 'Microsoft 365 / Outlook'), ('gmail', 'Gmail'), ('imap', 'IMAP-compatible server')], max_length=20)),
                ('transport', models.CharField(choices=[('imap', 'IMAP / IMAP OAuth2'), ('graph', 'Microsoft Graph API'), ('gmail_api', 'Gmail API')], default='imap', max_length=20)),
                ('auth_method', models.CharField(choices=[('password', 'Password / app password'), ('oauth2', 'OAuth2')], default='oauth2', max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('folder', models.CharField(default='INBOX', max_length=255)),
                ('is_shared_mailbox', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=True)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('polling_interval_seconds', models.PositiveIntegerField(default=60)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('sync_cursor', models.TextField(blank=True)),
                ('encrypted_credentials', models.TextField(blank=True, editable=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('site_name', models.CharField(max_length=120)),
                ('contractor', models.CharField(blank=True, max_length=160)),
                ('report_type', models.CharField(max_length=120)),
                ('rig_name', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('due_time', models.TimeField()),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='ISO weekday numbers (1=Monday, 7=Sunday). Empty means every day.')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('notification_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_name', 'report_type'],
            },
        ),
        migrations.CreateModel(
            name='SenderRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('email', 'Email address'), ('domain', 'Domain')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('blocked', 'Blocked')], default='approved', max_length=10)),
                ('site_name', models.CharField(blank=True, max_length=120)),
                ('contractor', models.CharField(blank=True, max_length=160)),
                ('default_department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['match_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=512)),
                ('message_id', models.CharField(max_length=998)),
                ('thread_id', models.CharField(blank=True, max_length=998)),
                ('in_reply_to', models.CharField(blank=True, max_length=998)),
                ('references', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_email', models.FileField(max_length=500, upload_to=email_reports.models.original_email_path)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('review', 'Needs human review'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('is_authorized_sender', models.BooleanField(default=False)),
                ('site_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('contractor', models.CharField(blank=True, max_length=160)),
                ('report_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('rig_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reporting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('classification_result', models.JSONField(blank=True, default=dict)),
                ('extraction_result', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='email_reports.emailaccount')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='email_reports.emailmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(max_length=500, upload_to=email_reports.models.attachment_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('unsupported', 'Unsupported'), ('invalid', 'Invalid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_members', to='email_reports.emailattachment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_reports.emailmessage')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='MissingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('received_late', 'Received late'), ('resolved', 'Resolved'), ('waived', 'Waived')], db_index=True, default='missing', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expected_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_instances', to='email_reports.expectedreport')),
                ('received_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_missing_reports', to='email_reports.emailmessage')),
            ],
            options={
                'ordering': ['-reporting_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='email_reports.emailmessage')),
                ('related_missing_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='email_reports.missingreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='email_reports.emailmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='email_reports.emailmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='senderregistry',
            constraint=models.UniqueConstraint(fields=('match_type', 'value'), name='email_sender_registry_match_unique'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['site_name', 'report_type', 'reporting_date'], name='email_repor_site_na_6594ff_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['sender_email', 'received_at'], name='email_repor_sender__20c003_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('account', 'message_id'), name='email_message_account_id_unique'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['checksum_sha256', 'size_bytes'], name='email_repor_checksu_9c06f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='missingreport',
            constraint=models.UniqueConstraint(fields=('expected_report', 'reporting_date'), name='email_missing_report_unique'),
        ),
    ]
