# Generated by Django 5.0.4 on 2026-04-01 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RigDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rig', models.CharField(db_index=True, max_length=30)),
                ('operating_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('standby_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('breakdown_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ilm_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('zero_rate_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Standby', 'Standby'), ('Breakdown', 'Breakdown')], default='Running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'rig'],
                'indexes': [models.Index(fields=['date'], name='core_rigdai_date_1d99c7_idx'), models.Index(fields=['rig'], name='core_rigdai_rig_8ab501_idx'), models.Index(fields=['zero_rate_hours'], name='core_rigdai_zero_ra_6aef19_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rigdailylog',
            constraint=models.CheckConstraint(check=models.Q(('operating_hours__gte', 0), ('standby_hours__gte', 0), ('breakdown_hours__gte', 0), ('ilm_hours__gte', 0), ('zero_rate_hours__gte', 0)), name='rdl_no_negative_hours'),
        ),
        migrations.AlterUniqueTogether(
            name='rigdailylog',
            unique_together={('rig', 'date')},
        ),
    ]
