# Generated by Django 5.0.4 on 2026-04-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_rigs',
            field=models.CharField(blank=True, default='', help_text='Comma-separated rig names. Empty = access to ALL rigs', max_length=500),
        ),
    ]
