# Generated by Django 5.0.4 on 2026-04-01 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_no', models.CharField(max_length=30, unique=True)),
                ('registration_no', models.CharField(blank=True, help_text='Vehicle/equipment registration number', max_length=30)),
                ('equipment_type', models.CharField(choices=[('Crane', 'Crane'), ('Trailer', 'Trailer'), ('Forklift', 'Forklift'), ('Hydra', 'Hydra'), ('Generator', 'Generator'), ('Pump', 'Pump'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 50T, 30m3/hr', max_length=50)),
                ('year_of_mfg', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Deployed', 'Deployed'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Available', max_length=25)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['equipment_type', 'equipment_no'],
            },
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_name', models.CharField(max_length=30, unique=True)),
                ('rig_model', models.CharField(blank=True, max_length=80)),
                ('rig_type', models.CharField(blank=True, max_length=50)),
                ('horse_power', models.IntegerField(blank=True, null=True)),
                ('depth_capacity', models.IntegerField(blank=True, help_text='metres', null=True)),
                ('year_commissioned', models.IntegerField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('rig_status', models.CharField(choices=[('Active', 'Active'), ('Standby', 'Standby'), ('Breakdown', 'Breakdown'), ('Demobilised', 'Demobilised')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rig_name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(default='General', help_text='e.g. Trailer, Crane, Both, General', max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('contract_no', models.CharField(blank=True, max_length=50)),
                ('contract_from', models.DateField(blank=True, null=True)),
                ('contract_to', models.DateField(blank=True, null=True)),
                ('rate_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='WellLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('BWP', 'Block Well Pad (BWP)'), ('AWP', 'Area Well Pad (AWP)'), ('MWP', 'Main Well Pad (MWP)'), ('NI', 'New Installation (NI)'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'location'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_type', models.CharField(choices=[('Rig', 'Rig Operation'), ('ILM', 'ILM Move'), ('Location', 'Well Location'), ('Workshop', 'Workshop / Maintenance'), ('Yard', 'Yard / Storage')], default='Rig', max_length=20)),
                ('deployed_to', models.CharField(help_text='Rig name, location, or workshop name', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently deployed', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='masters.equipment')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='masters.vendor'),
        ),
    ]
