# Generated by Django 5.0.4 on 2026-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Crane', 'Crane'), ('Trailer', 'Trailer'), ('Forklift', 'Forklift'), ('Hydra', 'Hydra'), ('Generator', 'Generator'), ('Pump', 'Pump'), ('Vehicle', 'Vehicle'), ('Compressor', 'Compressor'), ('Excavator', 'Excavator'), ('Bulldozer', 'Bulldozer'), ('Grader', 'Grader'), ('Tanker', 'Tanker'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Other', 'Other')], max_length=20),
        ),
    ]
