# Generated by Django 5.0.4 on 2026-05-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('RigCarrier', 'RigCarrier'), ('Generator', 'Generator'), ('MudPump', 'MudPump'), ('Crane', 'Crane'), ('Trailer', 'Trailer'), ('Forklift', 'Forklift'), ('Hydra', 'Hydra'), ('Vehicle', 'Vehicle'), ('Compressor', 'Compressor'), ('Ambulance', 'Ambulance'), ('Pump', 'Pump'), ('Tanker', 'Tanker'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Other', 'Other')], max_length=20),
        ),
    ]
