# Generated by Django 5.0.4 on 2026-04-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ILMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rig', models.CharField(db_index=True, max_length=30)),
                ('move_status', models.CharField(choices=[('Active', 'Active — Rig Moving'), ('Standby', 'Standby — Waiting'), ('Internal', 'Internal Move'), ('Idle', 'Idle — No Activity')], default='Active', max_length=20)),
                ('ilm_from_location', models.CharField(blank=True, max_length=150)),
                ('ilm_to_location', models.CharField(blank=True, max_length=150)),
                ('distance_kms', models.CharField(blank=True, help_text='Can be multi-leg: 46 & 3.9', max_length=50)),
                ('expected_ilm_hrs', models.CharField(blank=True, help_text='Can be multi-leg: 54 & 30', max_length=20)),
                ('during_ilm_hrs', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours taken', max_digits=5, null=True)),
                ('rig_move_extra_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rig_move_saving_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trailer_reported', models.IntegerField(default=0)),
                ('trailer_loss', models.IntegerField(default=0)),
                ('trailer_vendor', models.CharField(blank=True, max_length=150)),
                ('crane_reported', models.CharField(blank=True, help_text='Count or description e.g. 2, 1 ARC & 1 ACC', max_length=50)),
                ('crane_vendor', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilm_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'rig'],
            },
        ),
        migrations.CreateModel(
            name='ILMEquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Trailer', 'Trailer'), ('Crane', 'Crane'), ('Forklift', 'Forklift'), ('Hydra', 'Hydra'), ('Support', 'Support Vehicle'), ('Other', 'Other')], default='Trailer', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilm_usages', to='masters.equipment')),
                ('ilm_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usage', to='ilm.ilmlog')),
            ],
        ),
        migrations.AddIndex(
            model_name='ilmlog',
            index=models.Index(fields=['date'], name='ilm_ilmlog_date_9a60d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ilmlog',
            index=models.Index(fields=['rig'], name='ilm_ilmlog_rig_463fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='ilmlog',
            index=models.Index(fields=['move_status'], name='ilm_ilmlog_move_st_5e4a25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ilmequipmentusage',
            unique_together={('ilm_log', 'equipment')},
        ),
    ]
