# Generated by Django 5.0.4 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmlog',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='upto_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='upto_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]