# Generated by Django 5.0.4 on 2026-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0002_ilm_from_upto_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmlog',
            name='move_status',
            field=models.CharField(choices=[('Active', 'Active â€” Rig Moving'), ('Standby', 'Standby â€” Waiting'), ('Internal', 'Internal Move'), ('Idle', 'Idle â€” No Activity')], default='Active', max_length=20),
        ),
    ]
