# Generated by Django 5.0.4 on 2026-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0003_alter_ilmlog_move_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilmlog',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='ilmlog',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='ilmlog',
            name='upto_date',
        ),
        migrations.RemoveField(
            model_name='ilmlog',
            name='upto_time',
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='end_date',
            field=models.DateField(blank=True, help_text='ILM end date', null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='end_time',
            field=models.TimeField(blank=True, help_text='ILM end time', null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='start_date',
            field=models.DateField(blank=True, help_text='ILM start date', null=True),
        ),
        migrations.AddField(
            model_name='ilmlog',
            name='start_time',
            field=models.TimeField(blank=True, help_text='ILM start time', null=True),
        ),
        migrations.AlterField(
            model_name='ilmlog',
            name='move_status',
            field=models.CharField(choices=[('Active', 'Active — Rig Moving'), ('Standby', 'Standby — Waiting'), ('Internal', 'Internal Move'), ('Idle', 'Idle — No Activity')], default='Active', max_length=20),
        ),
    ]
