# Generated by Django 5.0.4 on 2026-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0004_remove_ilmlog_from_date_remove_ilmlog_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmlog',
            name='move_group',
            field=models.CharField(blank=True, default='', help_text='Group ID linking multi-day entries of same ILM move', max_length=50),
        ),
    ]
