# Generated by Django 5.0.4 on 2026-05-04 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POBDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig', models.CharField(db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, help_text='AWP/MWP number', max_length=50)),
                ('lti_free_days', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'rig'],
                'unique_together': {('rig', 'date')},
            },
        ),
        migrations.CreateModel(
            name='POBPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VEDANTA_PERSON', 'Vedanta Person (Company Man)'), ('VEDANTA_VISITOR', 'Vedanta Visitor'), ('VEDANTA_SERVICE', 'Vedanta Services'), ('VEDANTA_DRIVER', 'Vedanta Driver'), ('KS_DRILLING', 'KS Drilling Crew'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], db_index=True, default='KS_DRILLING', max_length=30)),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(blank=True, choices=[('D', 'Day'), ('N', 'Night'), ('G', 'General')], max_length=2)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('accommodation', models.CharField(blank=True, max_length=150)),
                ('room_no', models.CharField(blank=True, max_length=50)),
                ('doj', models.DateField(blank=True, help_text='Date of joining site', null=True)),
                ('days_on_site', models.IntegerField(default=0)),
                ('nationality', models.CharField(default='INDIAN', max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('meal_b', models.BooleanField(default=False, verbose_name='Breakfast')),
                ('meal_l', models.BooleanField(default=False, verbose_name='Lunch')),
                ('meal_d', models.BooleanField(default=False, verbose_name='Dinner')),
                ('arrived', models.BooleanField(default=False)),
                ('left_site', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('pob_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='pob.pobdailylog')),
            ],
            options={
                'ordering': ['category', 'sno', 'name'],
            },
        ),
    ]
