# Generated by Django 5.0.4 on 2026-05-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POBAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POBCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POBDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pobperson',
            name='accommodation_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pobperson',
            name='company_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pobperson',
            name='designation_text',
            field=models.CharField(blank=True, help_text='Free text if not in master', max_length=100),
        ),
        migrations.AddField(
            model_name='pobperson',
            name='room_no_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pobdailylog',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='category',
            field=models.CharField(choices=[('VEDANTA_PERSON', 'Vedanta Person'), ('VEDANTA_VISITOR', 'Vedanta Visitor'), ('VEDANTA_SERVICE', 'Vedanta Services'), ('VEDANTA_DRIVER', 'Vedanta Driver'), ('KSD_CREW', 'KSD Drilling Crew'), ('CONTRACTOR', 'Contractor / Vendor'), ('OTHER', 'Other')], db_index=True, default='KSD_CREW', max_length=30),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='meal_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='meal_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='meal_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='shift',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('N', 'Night'), ('G', 'General')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_persons', to='pob.pobaccommodation'),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_persons', to='pob.pobcompany'),
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_persons', to='pob.pobdesignation'),
        ),
        migrations.CreateModel(
            name='POBRoomNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pob.pobaccommodation')),
            ],
            options={
                'ordering': ['accommodation__name', 'room_no'],
            },
        ),
        migrations.AlterField(
            model_name='pobperson',
            name='room_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_persons', to='pob.pobroomno'),
        ),
    ]
