# Generated by Django 5.0.4 on 2026-05-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pob', '0002_pobaccommodation_pobcompany_pobdesignation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POBEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('rig', models.CharField(blank=True, help_text='Assigned rig', max_length=30)),
                ('shift', models.CharField(choices=[('D', 'Day'), ('N', 'Night'), ('G', 'General')], default='G', max_length=2)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(default='INDIAN', max_length=50)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='pob.pobcompany')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='pob.pobdesignation')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'unique_together': {('name', 'company')},
            },
        ),
    ]
