# Generated by Django 5.0.4 on 2026-04-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSDDailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rig', models.CharField(db_index=True, max_length=30)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, help_text='Stock at start of day (litres)', max_digits=10)),
                ('receipts', models.DecimalField(decimal_places=2, default=0, help_text='Total received during day (auto-computed)', max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, help_text='Total issued/consumed during day (auto-computed)', max_digits=10)),
                ('closing_stock', models.DecimalField(decimal_places=2, default=0, help_text='Stock at end of day (auto-computed)', max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsd_stock_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'rig'],
                'indexes': [models.Index(fields=['date'], name='hsd_hsddail_date_417325_idx'), models.Index(fields=['rig'], name='hsd_hsddail_rig_61dfa4_idx')],
                'unique_together': {('date', 'rig')},
            },
        ),
        migrations.CreateModel(
            name='HSDIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rig', models.CharField(db_index=True, help_text='Rig or location issuing from', max_length=30)),
                ('purpose', models.CharField(choices=[('Drilling', 'Drilling / Rig Engine'), ('Generator', 'Generator'), ('Equipment', 'Equipment (Crane/Trailer/Hydra)'), ('Vehicle', 'Vehicle / Transport'), ('Camp', 'Camp / Utility'), ('Other', 'Other')], default='Drilling', max_length=20)),
                ('issued_to', models.CharField(help_text='Rig name, equipment no, or description', max_length=100)),
                ('quantity_ltrs', models.DecimalField(decimal_places=2, help_text='Quantity issued in litres', max_digits=10)),
                ('issued_by', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsd_issues', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, help_text='Link to fleet equipment if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsd_issues', to='masters.equipment')),
            ],
            options={
                'ordering': ['-date', 'rig'],
                'indexes': [models.Index(fields=['date'], name='hsd_hsdissu_date_147e0c_idx'), models.Index(fields=['rig'], name='hsd_hsdissu_rig_94576b_idx'), models.Index(fields=['purpose'], name='hsd_hsdissu_purpose_d8dc47_idx')],
            },
        ),
        migrations.CreateModel(
            name='HSDReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('receipt_no', models.CharField(blank=True, help_text='Challan / Invoice number', max_length=50)),
                ('rig', models.CharField(db_index=True, help_text='Rig or location receiving the diesel', max_length=30)),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier name if not in vendor master', max_length=100)),
                ('vehicle_no', models.CharField(blank=True, help_text='Tanker vehicle number', max_length=30)),
                ('quantity_ltrs', models.DecimalField(decimal_places=2, help_text='Quantity received in litres', max_digits=10)),
                ('rate_per_ltr', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per litre (₹)', max_digits=8, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_by', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsd_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Fuel supplier vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsd_receipts', to='masters.vendor')),
            ],
            options={
                'ordering': ['-date', 'rig'],
                'indexes': [models.Index(fields=['date'], name='hsd_hsdrece_date_ee340e_idx'), models.Index(fields=['rig'], name='hsd_hsdrece_rig_d3c30b_idx')],
            },
        ),
    ]
