# Generated by Django 5.0.4 on 2026-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsdissue',
            name='meter_end',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ending meter/hour reading', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hsdissue',
            name='meter_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours run (auto = end - start)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hsdissue',
            name='meter_start',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Starting meter/hour reading', max_digits=10, null=True),
        ),
    ]
